---

- name: Rôle d'install et config d'une machine wordpress ready
  hosts: web
  become: true
  become_user: root
  vars_files: 
    - ../vars/main.yml
    - ../vaults/db-secrets.yml

  roles:
    - geerlingguy.apache
  
  tasks: 
    - name: Installation et configuration packets nécessaires wordpress
      ansible.builtin.apt:
        name: 
        -  ghostscript
        -  libapache2-mod-php
        -  php
        -  php-bcmath
        -  php-curl
        -  php-imagick
        -  php-intl
        -  php-json
        -  php-mbstring
        -  php-mysql
        -  php-xml
        -  php-zip 

    - name: Créer le directory de gestion d'install wordpress
      ansible.builtin.file:
        path: /var/www/wordpress
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data
    
    - name: Télécharger et extraire wordpress
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/
        remote_src: true
    
    - name: Changer les permissions du dossier wordpress
      ansible.builtin.file:
        path: /var/www/wordpress
        owner: www-data
        group: www-data

    - name: Configuration fichier wp-config.php
      ansible.builtin.template:
        src: ../templates/wp-config.j2
        dest: /var/www/wordpress/wp-config.php
        mode: "0644"

...
